<?xml version="1.0"?>
<package format="2">
  <name>tiago_pro_robot</name>
  <version>0.0.13</version>
  <description>The tiago_pro_robot package</description>

  <maintainer email="narcis.miguel@pal-robotics.com">Narcis Miguel</maintainer>

  <license>Propietary</license>

  <buildtool_depend>catkin</buildtool_depend>
  <exec_depend>tiago_pro_bringup</exec_depend>
  <exec_depend>tiago_pro_controller_configuration</exec_depend>
  <exec_depend>tiago_pro_description</exec_depend>

  <export>
    <metapackage/>
  </export>
</package>
